### ISSUE TITLE
Add "hacktoberfest" repository topic

### ISSUE THREAD

**Issue by taniotanio7** [30-seconds/30-seconds-of-react#107]
Please add the "hacktoberfest" repository topic to allow completion of the Hacktoberfest challenge 🙏 
It's already present on the [30-seconds-of-code](https://github.com/30-seconds/30-seconds-of-code) repository 😉

**Comment by Chalarangelo** [comment]
Sorry, but we've made a conscious decision here to not accept snippets in all repositories due to the high amounts of new users trying to contribute and the large amount of spam PRs we are getting. For this year's Hacktoberfest we are only accepting content in the JS and Python repos, so no `hacktoberfest` topic or `hacktoberfest-accepted` on any other repos. Cheers.
